### ISSUE TITLE
Runtime crash caused by permutation parsing with Optimization flag

### ISSUE THREAD

**Issue by konn** [ekmett/parsers#16] opened 2013-07-11 08:19 UTC
Consider the following code:

``` haskell
module Main where
import Control.Applicative
import Text.Parser.Permutation
import Text.Trifecta

main :: IO ()
main =  parseTest (myPerm "a") "semanticsppp"

myPerm :: String -> Parser (String, String, String)
myPerm opN = permute $
   (,,) opN <$$> string "semantics"
            <|?> ([], (some (char 'p')))
```

If I compile this code with `-O2` flag with GHC 7.6.3, this program halt with runtime crash:

``` zsh
$ ghc -O2 crash.hs
[1 of 1] Compiling Main             ( crash.hs, crash.o )
Linking crash ...

$ ./crash
crash: Oops!  Entered absent arg w_s3DL{v} [lid] base:GHC.Base.String{tc 36u}
```

If I compile the same code without `-O2` flag, then it runs without fail:

``` zsh
$ ghc -O0 crash.hs -fforce-recomp
[1 of 1] Compiling Main             ( crash.hs, crash.o )
Linking crash ...

$ ./crash                        
("a","semantics","ppp")
```

It might be GHC's bug, but I couldn't find out what caused this.

**Comment by RyanGlScott** [comment] 2018-02-11 00:14
Indeed, I think it's likely to be one of these old GHC Trac tickets: https://ghc.haskell.org/trac/ghc/search?q=%22Entered+absent+arg%22

I can't reproduce this issue on a modern GHC (8.2.2), so I'm opting to close this. Do reopen if you can trigger the issue on a more recent GHC.

**Closed by RyanGlScott** 2018-02-11 00:14 UTC
